groups:
  - name: test-alerts
    rules:
    - alert: Watchdog
      expr: vector(1)
      for: 1m
      labels:
        severity: none
      annotations:
        summary: "Test connection Prometheus & Alertmanager"
        description: "Pipeline is working"

