---
- name: Ensure docker installed
  hosts: monitorting_core
  become: true
  roles:
    - geerlingguy.docker


- name: Deploy LGTM Stack
  hosts: monitorting_core
  become: true
  roles:
    - core
