# SPDX-License-Identifier: MIT-0
---
# handlers file for core
- name: Wait for Alloy is ready
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 12345
    state: started
    delay: 2
    timeout: 30
  listen: "Reload Alloy"

- name: Send request to Alloy reload
  ansible.builtin.uri:
    url: http://127.0.0.1:12345/-/reload
    method: GET
    status_code: 200
  register: core_alloy_reload
  listen: "Reload Alloy"

- name: Show Alloy reload results
  ansible.builtin.debug:
    var: core_alloy_reload.content
  listen: "Reload Alloy"
