# SPDX-License-Identifier: MIT-0
---
# handlers file for core

# Grafana Alloy
- name: Alloy reload
  ansible.builtin.include_tasks: alloy_reload.yml

# Prometheus
- name: Prometheus reload
  ansible.builtin.include_tasks: prometheus_reload.yml

# Grafana
- name: Grafana reload
  ansible.builtin.include_tasks: grafana_reload.yml

- name: Loki reload
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    services:
      - loki
    state: restarted

- name: Blackbox reload
  ansible.builtin.include_tasks: blackbox_reload.yml
