---
- name: Ensure prometheus directories exists
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: rm
    group: rm
    mode: "0755"
  loop:
    - /opt/monitoring/prometheus
    - /opt/monitoring/prometheus/targets

- name: Copy prometheus.yml to prometheus directory
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/monitoring/prometheus/prometheus.yml
    owner: rm
    group: rm
    mode: "0755"
  notify: Prometheus reload

- name: Copy Prometheus targets from template
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/opt/monitoring/prometheus/targets/{{ item }}"
    owner: rm
    group: rm
    mode: "0644"
  loop:
    - blackbox_targets.yml