# SPDX-License-Identifier: MIT-0
---
# vars file for core
core_alloy_version: v1.12.2
core_alloy_port: 12345

core_prometheus_version: v3.9.0
core_prometheus_addr: prometheus
core_prometheus_port: 9090
core_prometheus_retention_time: 30d
core_prometheus_retention_size: 5GB

core_grafana_version: 12.3.1
core_grafana_port: 3000

core_minio_version: RELEASE.2025-09-07T16-13-09Z
core_minio_port_api: 9000
core_minio_port_ui: 9001

core_loki_version: 3.6
core_loki_port: 3100

core_blackbox_version: v0.28.0
core_blackbox_port: 9115
