# SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Creating monitoring directory
  ansible.builtin.file:
    state: directory
    path: /opt/monitoring
    owner: rm
    group: rm
    mode: "0755"
    recurse: true
