{
 "title": "Podinfo Test Sandbox",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"cadvisor:8081\"},name)"
    }
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": {
     "query": "label_values(http_requests_total,status)"
    }
   },
   {
    "name": "blackbox_instance",
    "label": "Blackbox Instance",
    "query": {
     "query": "label_values({__name__=~\"probe.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(container_memory_usage_bytes{name=\"alloy\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 containers by CPU usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (name) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Transmit by Container",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{name=~\"$container\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Blackbox Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"$blackbox_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"$blackbox_instance\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "HTTP Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$blackbox_instance\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$blackbox_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=\"$blackbox_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"$blackbox_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"$blackbox_instance\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg HTTP Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, probe_duration_seconds{instance=\"$blackbox_instance\"}[$__range])",
     "legendFormat": "Median"
    },
    {
     "expr": "quantile_over_time(0.99, probe_duration_seconds{instance=\"$blackbox_instance\"}[$__range])",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}